### ISSUE TITLE
Most service/tool descriptions are drawn directly from marketing copy

### ISSUE THREAD

**Issue by webmaven** [cjbarber/ToolsOfTheTrade#120]
Can we submit PRs that will make the descriptions more objective?

**Comment by davisonio** [comment]
Definitely a good idea. Some of the descriptions here are too marketing-focues or verbose and should be summarised. If anyone wants to help with this, even by choosing just one section to work on, this would be great help! :smiley:

**Comment by webmaven** [comment]
@cjbarber, can you weigh in on whether PRs improving the descriptions to make them more objective would be accepted?

**Comment by davisonio** [comment]
> @cjbarber, can you weigh in on whether PRs improving the descriptions to make them more objective would be accepted?

@cjbarber is not as active on this project anymore. I would definitely accept PRs that add/improve descriptions. Lots of them need to be more to the point and less biased.

**Comment by webmaven** [comment]
Thanks, @davisonio, just what I needed to hear! :smile:

**Comment by webmaven** [comment]
P.S. I suggest expanding the *Contributing* section with some info on the kinds of contributions that would be welcome as PRs vs. filed as Issues, and the people currently active as maintainer.

**Comment by davisonio** [comment]
> P.S. I suggest expanding the Contributing section with some info on the kinds of contributions that would be welcome as PRs vs. filed as Issues, and the people currently active as maintainer.

Done in https://github.com/cjbarber/ToolsOfTheTrade/commit/8f048035862919ab945cbf9da14b41f0b0c15211 :)
