### ISSUE TITLE
Would this page look better using tables?

### ISSUE THREAD

**Issue by voltagex** [cjbarber/ToolsOfTheTrade#14]
The list may be easier to read using tables, but I haven't tried it yet.

https://help.github.com/articles/github-flavored-markdown#tables

**Comment by davisonio** [comment]
Here's an example of what the 'Continuous Integration' section may look like: https://gist.github.com/davisonio/be42b516b5f40e581318cd62516bea6f ...not too nice. Scrollbars would be needed at the bottom and the descriptions take up a large amount of spaces.

Here's my proposal, **change this**:
```
BlockScore | https://blockscore.com | @getblockscore | $1/verification | Individual ID verifications and company verifications, verify customers in realtime. Implement in hours
```
rendered as:
* BlockScore | https://blockscore.com | @getblockscore | $1/verification | Individual ID verifications and company verifications, verify customers in realtime. Implement in hours.

**To this**:
```
- [BlockScore](https://blockscore.com) - Individual ID verifications and company verifications, verify customers in realtime. Implement in hours (**$1/verification**, [@getblockscore](https://twitter.com/getblockscore))
```

rendered as:

- [BlockScore](https://blockscore.com) - Individual ID verifications and company verifications, verify customers in realtime. Implement in hours (**$1/verification**, [@getblockscore](https://twitter.com/getblockscore))
