### ISSUE TITLE
Add Assembla in Source Code Hosting section.

### ISSUE THREAD

**Issue by tiagobarreto** [cjbarber/ToolsOfTheTrade#151]
Add Assembla (https://www.assembla.com/) in Source Code Hosting section.

**Comment by davisonio** [comment]
Maybe you could create a pull request that adds this?

**Comment by tiagobarreto** [comment]
@davisonio yes, I will to create now. :)

**Comment by davisonio** [comment]
https://github.com/cjbarber/ToolsOfTheTrade/commit/ffd772ec5af8b9e106036cbfe58be81acbf69d97 :tada:
