### ISSUE TITLE
Add stathat (unsure where to put it)

### ISSUE THREAD

**Issue by vrillusions** [cjbarber/ToolsOfTheTrade#170]
```
* stathat | https://www.stathat.com | [@stathat](https://twitter.com/stathat) | free (first 10, min granularity 15 minutes) - $99/mo (unlimited, 1 minute granularity) | StatHat tracks numbers from anywhere in your code. In just 1 line, you can embed it. Invent stats on the fly. Track data instantly, up to the minute, accurately
```

so it could fit in to a bunch of categories (traffic analytics, user analytics, app performance, data, etc).  Perhaps a new category called "Data Graphing"? a couple others that would fit there is [munin](http://munin-monitoring.org/) and [graphite](http://graphite.wikidot.com/)

**Comment by davisonio** [comment]
I think that this would be best under the 'Data' heading. Maybe you could make a pull request that adds this?
