### ISSUE TITLE
facebookConnectPlugin.api is not working

### ISSUE THREAD

**Issue by deogadekunal** [cjbarber/ToolsOfTheTrade#180]
I am using cordova 3.5.0 and android facebook sdk 3.8, below code is not working which is inside onDeviceReady function. "facebookConnectPlugin.api" method is not getting called, here is the actual code

facebookConnectPlugin.api('/me', function(response) 
				{
					alert("facebookConnectPlugin.api");
					if (response.error) 
					{
						console.log('Unexpected Facebook Login Error: ' + JSON.stringify(response.error));
			            showAlertNotification('Error! Try Again..');
					}
					else 
					{
						console.log(response);
			            var login_data = '';
						for (var key in response) 
						{
							if (key == 'id' || key == 'name' || key == 'email' || key == 'gender')
							login_data += key + '=' + encodeURIComponent(response[key]) + '&';
						}
						if (login_data.length > 0) 
						{
							login_data = login_data.substring(0, login_data.length - 1);
						}
							// save to your db or apply ur custom logic
					}
				});
			}

**Comment by davisonio** [comment]
You're probably looking to post this issue here: https://github.com/Wizcorp/phonegap-facebook-plugin
