### ISSUE TITLE
database alerts

### ISSUE THREAD

**Issue by miguelitomola** [cjbarber/ToolsOfTheTrade#267]
Hello, 

I'm in charge of a server that hosts a wordpress website and, from time to time, the mysql database crashes . Then, it must be restarted. Therefore I'm looking for a service that generates email / sms alerts when the database crashes. As the list of tools is big I will appreciate it if someone can help.

**Comment by bcambel** [comment]
you may also use a website monitoring tool to ping the website and check if the answer is valid otherwise you will receive a notification. Check  https://www.pingdom.com http://newrelic.com

**Comment by miguelitomola** [comment]
Thank you bcambel, I've just registered to pingdom.com . Pingdom.com checks HTTP / HTTPS connections to the server which could be right even if mysql server is down, isn't it?

**Comment by bcambel** [comment]
Just to be clear, Pingdom will only check if your server (website) responds
as you expected or not.
It will have nothing to do with the mysql. Your webserver might be down (
Apache ) or database or your machine might be down. At the end of the day,
what you care is if your website is up and running or not.

On Tue, Jul 21, 2015 at 4:13 PM, miguelitomola <notifications@github.com>
wrote:

> Thank you bcambel, I've just registered to pingdom.com . Pingdom.com
> checks HTTP / HTTPS connections to the server which could be right even if
> mysql server is down, isn't it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cjbarber/ToolsOfTheTrade/issues/267#issuecomment-123326684>
> .
>



-- 
Regards ,
Bahadir Cambel

**Comment by miguelitomola** [comment]
Ok, so in case the database (mysql) is down, the website won't respond as I expected and pingdom will mark the status as down. This was indeed what I was looking for. Thank you very much.

**Comment by jackeblagare** [comment]
What you can do is create a script that Pingdom accesses. Inside that script, you can check whether the database is responding or not among other things. If the script returns an OK, Pingdom will know that everything is running well. If the script doesn't return an OK, Pingdom also tells you that there's something wrong with your site.

**Comment by davisonio** [comment]
I hope you've solved your issue @miguelitomola :)
