### ISSUE TITLE
Please add a license to the repo

### ISSUE THREAD

**Issue by mbrukman** [cjbarber/ToolsOfTheTrade#275]
Could you please add an explicit LICENSE file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license):

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

For example, [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) (aka _CC BY 4.0_), could be a good choice here since the content is text, not code.

Thanks!

**Comment by mbrukman** [comment]
@davisonio — I see you've thumbed-up and closed this issue, but I don't see a `LICENSE` file in the repo, nor a license mention/note anywhere in the readme. Did I miss it perhaps?

**Comment by davisonio** [comment]
I'm unable to add a license at the moment because I'll need permission from @cjbarber and don't see that changing in the future

**Comment by mbrukman** [comment]
Can we keep this issue open then, and assign it to @cjbarber for a decision?

**Comment by davisonio** [comment]
Sure, I'd be happy with CC0

**Comment by davisonio** [comment]
@cjbarber great stuff! happy with that
