### ISSUE TITLE
Price rules

### ISSUE THREAD

**Issue by ghost** [cjbarber/ToolsOfTheTrade#301]
Some services show prices by month like 12$ and you think this super deal. But when you visit page its show 50$ because price is reduced when you paid annually or yearly

That create conflict, and question is `ToolsOfTheTrade` should show real prices by month or manipulated discount.

**Comment by mLuby** [comment]
also sometimes there are free tiers for open-source, which appear inconsistently applied. eg 
- TravisCI: free open source, $69/mo 1 private job, $129/mo 2 private jobs
- CircleCI: free open source, free 1 private job, $50/mo 2 private jobs

**Comment by davisonio** [comment]
Sure if anyone has any improvements for pricing rules, feel free to make a PR

**Comment by davisonio** [comment]
Closing for now due to inactivity
