### ISSUE TITLE
Prometheus Server Monitoring

### ISSUE THREAD

**Issue by michaelplemmons** [cjbarber/ToolsOfTheTrade#364]
Prometheus is a server monitoring tool - https://prometheus.io/

**Comment by deepakmaurya** [comment]
This is test comment through API

**Comment by deepakmaurya** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done
`<hr>`
**This issue now has a funding of 0.999 ETH (198.75 USD @ $198.95/ETH) attached to it.**

- If you would like to work on this issue you can 'start work' [https://github.com/jneen/rouge/issues/987](on the Gitcoin Issue Details page)
- Want to chip in? Add your own contribution here.
- Questions? Checkout Gitcoin Help or the Gitcoin Slack
- $31,424.97 more funded OSS Work available on the Gitcoin Issue Explorer

**Comment by davisonio** [comment]
Added in https://github.com/cjbarber/ToolsOfTheTrade/commit/8cd99a36109efb6caace98ccf735c28ba19e48da
