### ISSUE TITLE
Aplhabetically sorting Contents?

### ISSUE THREAD

**Issue by bmcminn** [cjbarber/ToolsOfTheTrade#380]
Discovering categories within the table of Contents requires scanning the entire list. If I want to reference "Phone" services, being able to scan down to the "P-----" section would help.

This could be automated to ease managing in the future.

**Comment by davisonio** [comment]
Happy for anyone to take on this task

**Comment by mattpavelle** [comment]
Just did this - pull request #417

**Comment by davisonio** [comment]
Closing, this will be fixed once #417 is merged
