### ISSUE TITLE
Data extracted with Apify to JSON/CSV/XLS

### ISSUE THREAD

**Issue by metamn** [cjbarber/ToolsOfTheTrade#385]
I've crawled the site and extracted the data with Apify. The crawler code and the results can be found at https://www.apify.com/metamn/2MS8r-api-https-github-com-cjbarber-toolsofthetrade

I've attached the JSOn, CSV and XLS versions of the data.

Cheers :)

[results.zip](https://github.com/cjbarber/ToolsOfTheTrade/files/2377929/results.zip)

**Comment by davisonio** [comment]
Have added this to the readme, hopefully works with the new table format :) https://github.com/cjbarber/ToolsOfTheTrade/commit/3ad8c685351458dd68620e071f1a2efdd5d832b8
