### ISSUE TITLE
Incorrect / old pricing for Mandrill in Transactional Email + missing service SparkPost

### ISSUE THREAD

**Issue by jamesallsup** [cjbarber/ToolsOfTheTrade#401]
It was changed quite some time ago where you are now required to subscribe to the Mailchimp service and also buy blocks of emails on top (blocks of 10k). It was a great service but was its downfall for most users.

Sparkpost ran a great "welcome Mandrill users" marketing spree on it and matched the free limits they also offered from Mandrill. 

They still offer a 15k/month free service. [Sparkpost Link](https://www.sparkpost.com/)

Mandrill to Sparkpost migration guide - https://www.sparkpost.com/migration-guides/mandrill/

**Comment by davisonio** [comment]
Have removed Mandrill thanks!
