### ISSUE TITLE
Online IDEs

### ISSUE THREAD

**Issue by styfle** [cjbarber/ToolsOfTheTrade#404]
I'm not sure if this is out of scope, but a tool/service that a developer might use is an Online IDE to write and deploy code.

I have a list of [Awesome Online IDEs](https://github.com/styfle/awesome-online-ide) but I don't want to duplicate this list here.

Would you like a link from ToolsOfTheTrade to awesome-online-ide?

**Comment by davisonio** [comment]
Just added a link! https://github.com/cjbarber/ToolsOfTheTrade/commit/a6cc4581f8f4f87464413571f50daec26bd401c3
