### ISSUE TITLE
New section - Boilerplates

### ISSUE THREAD

**Issue by wscourge** [cjbarber/ToolsOfTheTrade#461]
Hi there, I'd like to add a new section to this awesome repo that I've discovered recently and [am currently updating](https://github.com/cjbarber/ToolsOfTheTrade/pull/460) with little pieces that I know and have tested in my workflow.

The new section would be **Boilerplates** or maybe **Generators**? I am open to suggestions on naming it.

In the first iteration, if you'd allow me to work on it, I'd like to add there:

### Boilerplates

| Service | Twitter | Pricing | Description |
|:--------|:--------|:--------|:------------|
| [Yeoman](https://yeoman.io/) | [@yeoman](https://twitter.com/yeoman) | Free | The web scaffolding tool for modern web apps |
| [Hix on Rails](https://hixonrails.com/) | [@hixonrails](https://twitter.com/hixonrails) | $39 - $249 | Ruby on Rails project generator |
| [JHipster](https://www.jhipster.tech/) | [@jhipster](https://twitter.com/jhipster) | Free | Hipster stack for Java developers. Spring Boot + Angular/React in one handy generator. |
| [Divjoy](https://divjoy.com/) | [@divjoy](https://twitter.com/divjoy) | $59 | The React codebase generator. |
| [WPPB](https://wppb.me/) | - | Free | WordPress Plugin Boilerplate Generator |

Those are just those tools that I tested personally at some point - I'm sure that there are more!

---

Addressing your Contributing guide:

### Yeoman

- [x] Hosted
- [x] [HackerNews coverage](https://hn.algolia.com/?dateRange=all&page=0&prefix=true&query=yeoman&sort=byPopularity&type=story)
- [x] Concise, descriptive and not a marketing-focused description
- [x] Non-internationalized link

### Hix on Rails

One disclaimer here: I'm the author of this product.

- [x] Hosted
- [x] [HackerNews coverage](https://hn.algolia.com/?dateRange=all&page=0&prefix=false&query=hix%20on%20rails&sort=byPopularity&type=story)
- [x] Concise, descriptive and not a marketing-focused description
- [x] Non-internationalized link

### JHipster

- [x] Hosted
- [x] [HackerNews coverage](https://hn.algolia.com/?dateRange=all&page=0&prefix=true&query=jhipster&sort=byPopularity&type=story)
- [x] Concise, descriptive and not a marketing-focused description
- [x] Non-internationalized link

### Divjoy

- [x] Hosted
- [x] [HackerNews coverage](https://hn.algolia.com/?dateRange=all&page=0&prefix=true&query=divjoy&sort=byPopularity&type=story)
- [x] Concise, descriptive and not a marketing-focused description
- [x] Non-internationalized link

### WPPB

I'm open to removing it due to lack of HackerNews coverage if you decide to do so, but speaking from experience - it is a great tool. I've built 7 custom plugins using it so far, and it helped a lot, saving lots of time.

- [x] Hosted
- [ ] HackeNews coverage
- [x] Concise, descriptive and not a marketing-focused description
- [x] Non-internationalized link

Please let me know if you'd like me to proceed with PR for the proposed improvement.

Cheers, and keep up the good work!

**Comment by davisonio** [comment]
I'm happy with this - feel free to create a PR and I will merge. Thanks for doing this!

**Comment by wscourge** [comment]
It's great @davisonio - I did that, feel free to merge it whenever you like :rocket:

**Comment by davisonio** [comment]
All done - thx
