### ISSUE TITLE
Where might you see Forward Email being added?

### ISSUE THREAD

**Issue by niftylettuce** [cjbarber/ToolsOfTheTrade#465]
@cjbarber what section would this fall under?

https://forwardemail.net

**Comment by davisonio** [comment]
I would add under DNS

Feel free to create PR but add other changes when adding tool you're affiliated

**Comment by niftylettuce** [comment]
Will do @davisonio thank you

**Comment by niftylettuce** [comment]
Done!  I also submitted PR's for Lad and Cabin too, thank you so much @davisonio!
