### ISSUE TITLE
[Suggestion] Hierarchy to sort topics

### ISSUE THREAD

**Issue by GoulartNogueira** [cjbarber/ToolsOfTheTrade#497]
There are 86 topics (Contents), I think that's way too much for a single list.
I believe most of users have specific needs and would be way easier to find interesting by navigating through hierarchy sublists.
For example:
- Productivity
  - Task Scheduling
  - Time Tracking
  - ...
- Programming
  - Front End
  - ...
  - Back End
    - AWS Tools
    - Backend-aaS
    - ...
 - Marketing
   - SEO
   - Remote Collaboration
   - Remote Workers
   - ...
 - Payments
   - ...

**Comment by davisonio** [comment]
Good idea, would welcome this change if you'd or someone else would  like to take a crack at it

**Comment by GoulartNogueira** [comment]
I'll do my best.
