### ISSUE TITLE
Is it possible to request a tool to be added that I am working on?

### ISSUE THREAD

**Issue by TimothyBramlett** [cjbarber/ToolsOfTheTrade#503]
Hello!  I didn't see any contributing guidelines or a way to suggest a tool that I am working on.  Is that possible? :)

**Comment by davisonio** [comment]
Hey you can do but follow the rules on contributing guidelines

**Comment by TimothyBramlett** [comment]
@davisonio Oh sorry I am an idiot!  Did not see the `contributing.md` lol
